version: '3.1'
services:

  service:
    build: .
    ports:
      - "${SERVICE_PORTS}:${SERVICE_PORTS}"
    container_name: "apiservice"
    restart: always
    volumes:
      - /home/www-data/service/vendor
      - ./.env:/home/www-data/service/.env
      - ./api:/home/www-data/service/api
      - ./src:/home/www-data/service/src
      - ./db:/home/www-data/service/db
    env_file:
      - .env

  postgres:
    image: postgres:15
    container_name: "postgres"
    ports:
      - "5432:5432"
    environment:
      - POSTGRES_DB=${DB_NAME}
      - POSTGRES_USER=${DB_USER}
      - POSTGRES_PASSWORD=${DB_PASSWORD}
    volumes:
      - pgdata:/var/lib/postgresql/data

volumes:
  pgdata: